baseURL = "https://zhiecho.github.io/"
theme = "PaperMod"
title = "Zhiecho 的博客"
enableRobotsTXT = true
canonifyURLs = true
enableEmoji = true

[pagination]
  pagerSize = 10
  # path = "page"

[permalinks]
  # content/posts 下的文章将使用此 URL 结构
  posts = "/p/:year/:month/:day/:slug/"

[params]
  env = "production"
  description = "记录与分享"
  author = "Bakulman"
  keywords = ["博客", "技术", "生活"]
  defaultTheme = "auto"

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  # 想默认显示目录可加上：ShowToc = true
  comments = true

  [params.homeInfoParams]
    Title = "你好，我是 Bakulman"
    Content = "这里记录我的折腾与思考。"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/zhiecho"

  # （可选）giscus：你提供的配置已填好
  [params.giscus]
    repo = "bakulman/zhiecho.github.io"
    repoID = "R_kgDOPcdJDA"
    category = "Announcements"
    categoryID = "DIC_kwDOPcdJDM4CuFHA"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "dark"              # 或 preferred_color_scheme
    lang = "zh-CN"
    loading = "lazy"
    crossorigin = "anonymous"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# （可选）GA4：如需启用把下面一行改为你的 Measurement ID（形如 G-XXXXXXXXXX）
# googleAnalytics = "G-XXXXXXXXXX"
