name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo (extended, robust)
        env:
          HUGO_VERSION: "0.150.0"
        run: |
          set -euo pipefail
          OS="linux"
          ARCH="$(uname -m)"
          case "$ARCH" in
            x86_64) ARCH="amd64" ;;
            aarch64|arm64) ARCH="arm64" ;;
            *)
              echo "Unsupported arch: $(uname -m)"
              exit 1
              ;;
          esac

          TAR_URL="https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_${OS}-${ARCH}.tar.gz"
          DEB_URL="https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_${OS}-${ARCH}.deb"

          echo "Trying tarball: $TAR_URL"
          if curl -fLsS -o /tmp/hugo.tar.gz "$TAR_URL"; then
            if tar -tzf /tmp/hugo.tar.gz >/dev/null 2>&1; then
              tar -xzf /tmp/hugo.tar.gz -C /tmp
              sudo install -m 0755 /tmp/hugo /usr/local/bin/hugo
            else
              echo "Downloaded tar is not a valid gzip; showing headers:"
              curl -sIL "$TAR_URL" || true
              echo "Falling back to .deb…"
              curl -fLsS -o /tmp/hugo.deb "$DEB_URL"
              sudo dpkg -i /tmp/hugo.deb
            fi
          else
            echo "Tarball download failed; headers:"
            curl -sIL "$TAR_URL" || true
            echo "Falling back to .deb: $DEB_URL"
            curl -fLsS -o /tmp/hugo.deb "$DEB_URL"
            sudo dpkg -i /tmp/hugo.deb
          fi

          echo "Hugo installed:"
          hugo version

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
