name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Hugo (extended, auto-latest; no auth header)
        env:
          # 如需固定版本，改成例如 "0.149.1"；否则用 "latest"
          HUGO_VERSION: "latest"
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq ca-certificates

          # 取 tag
          if [ "${HUGO_VERSION:-latest}" = "latest" ] || [ -z "${HUGO_VERSION:-}" ]; then
            echo "Querying latest stable Hugo release…"
            TAG="$(curl -fsSL https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r .tag_name)"
          else
            TAG="v${HUGO_VERSION#v}"
          fi
          if ! printf '%s' "$TAG" | grep -q '^v'; then
            echo "Cannot determine tag. Got: $TAG"
            exit 1
          fi
          VER="${TAG#v}"
          echo "Using Hugo ${TAG}"

          # 拉取该 tag 的资产列表（匿名访问，不能带 GITHUB_TOKEN）
          curl -fsSL "https://api.github.com/repos/gohugoio/hugo/releases/tags/${TAG}" -o /tmp/hugo.json

          # 选 extended + linux + amd64 资产，优先 tar.gz，其次 deb
          pick_asset() {
            EXT="$1"
            jq -r --arg ext "$EXT" '
              .assets[] |
              select((.name|test("extended";"i")) and
                     (.name|test("linux";"i")) and
                     (.name|test("(amd64|x86_64)";"i")) and
                     (.name|endswith($ext))) |
              .browser_download_url' /tmp/hugo.json | head -n1
          }
          URL_TAR="$(pick_asset ".tar.gz" || true)"
          URL_DEB="$(pick_asset ".deb" || true)"

          if [ -n "${URL_TAR:-}" ] && [ "${URL_TAR}" != "null" ]; then
            echo "Downloading tarball: ${URL_TAR}"
            curl -fLsS -o /tmp/hugo.tar.gz "${URL_TAR}"
            tar -tzf /tmp/hugo.tar.gz >/dev/null
            tar -xzf /tmp/hugo.tar.gz -C /tmp
            # 定位 hugo 可执行文件
            BIN="$(tar -tzf /tmp/hugo.tar.gz | grep -E '(^|/)+hugo$' | head -n1 | sed 's#^\./##')"
            if [ -z "$BIN" ]; then
              echo "Cannot locate hugo binary in tarball."
              exit 1
            fi
            sudo install -m 0755 "/tmp/${BIN%/hugo}/hugo" /usr/local/bin/hugo
          elif [ -n "${URL_DEB:-}" ] && [ "${URL_DEB}" != "null" ]; then
            echo "Downloading deb: ${URL_DEB}"
            curl -fLsS -o /tmp/hugo.deb "${URL_DEB}"
            sudo dpkg -i /tmp/hugo.deb || sudo apt-get -f install -y
          else
            echo "No suitable linux amd64 extended asset found for ${TAG}."
            echo "Available assets:"
            jq -r '.assets[].name' /tmp/hugo.json || true
            exit 1
          fi

          echo "Hugo installed:"
          hugo version

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
